In [2]:
import numpy as np

array = np.array([range(i, i+3) for i in [2, 4, 6]])

array

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [3]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])